import Link from "next/link";
import { ArrowUpRight, CheckCircle2, Clock3, Flag, MapPin, Radio, Signal, Trophy } from "lucide-react";
import { drivers } from "../../drivers/page";
import { Number, PageHero, RaceButton, SectionTitle } from "../../../components/ui";

const registrationUrl = "https://docs.google.com/forms/d/e/1FAIpQLSdI6G9ifzZfCkr--Br_pUXWHUg9ngXYYjP4y9k_BHn2jPD3RQ/viewform?usp=header";
const category = { "Junior (under 18)": "Junior (moins de 18 ans)", General: "Général", Women: "Femmes", "Masters (40+)": "Masters (40+)", Master: "Master" };
const nationality = { Belgium: "Belgique", Denmark: "Danemark", France: "France", Germany: "Allemagne", Netherlands: "Pays-Bas", Poland: "Pologne", "United Kingdom": "Royaume-Uni" };

export default function FrenchPage({ params }) {
  const page = params.slug?.[0] || "home";
  if (page === "event") return <Event />;
  if (page === "live-timing") return <Timing />;
  if (page === "drivers") return <Drivers />;
  if (page === "rules") return <Rules />;
  if (page === "registration") return <Registration />;
  if (page === "contact") return <Contact />;
  return <Home />;
}

function Home() {
  return <><section className="relative min-h-[780px] overflow-hidden"><img src="/erw-track.png" alt="Circuit de karting indoor ERW à Experience Factory Eupen" className="absolute inset-0 h-full w-full object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-r from-black via-black/80 to-black/20" /><div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-black/40" /><div className="relative mx-auto flex min-h-[780px] max-w-7xl flex-col justify-center px-5 pb-16 pt-24 lg:px-8"><p className="text-xs font-black uppercase tracking-[.24em] text-red-500">Karting de location · Eupen</p><h1 className="mt-5 max-w-5xl font-display text-[4.8rem] font-black uppercase italic leading-[.8] tracking-[-.08em] sm:text-[7rem] lg:text-[9.4rem]">Road <span className="text-red-600">to</span><br />Worlds</h1><p className="mt-7 max-w-xl border-l-2 border-red-600 pl-5 text-base leading-7 text-neutral-300">Un circuit. Une grille. Chaque tour compte. ERW propose un format de karting de location de niveau mondial au cœur d'Eupen.</p><div className="mt-8 flex flex-wrap gap-3"><a href={registrationUrl} target="_blank" rel="noreferrer" className="inline-flex -skew-x-12 items-center gap-2 bg-red-600 px-6 py-4 text-xs font-black uppercase tracking-[.18em] transition hover:bg-red-500"><span className="skew-x-12">S'inscrire · €279</span></a><a href="https://docs.google.com/forms/d/e/1FAIpQLScAvcY5ULhrDERtKehVskvMarFnxj7nth2MN4HKyU75kbMOkQ/viewform?fbzx=-5429230602291440917" target="_blank" rel="noreferrer" className="inline-flex -skew-x-12 items-center gap-2 bg-red-600 px-6 py-4 text-xs font-black uppercase tracking-[.18em] transition hover:bg-red-500"><span className="skew-x-12">Réserver un entraînement · €20</span></a><RaceButton href="/fr/event" secondary>Découvrir l'événement</RaceButton></div></div></section><Info title="Pas de raccourci. Juste de la vitesse." copy="ERW est conçu autour d'une compétition équitable et d'un format qui récompense la régularité sous pression." /></>;
}

function Event() { return <><PageHero eyebrow="10–11 octobre · 2026" title="Week-end de course" text="Deux journées intenses de courses serrées, de matériel identique et de pression révélant les meilleurs pilotes." /><Info title="Le format" copy="Cinq courses de qualification par pilote. Les 60 meilleurs accèdent aux demi-finales, puis les 20 meilleurs à la grande finale." /></>; }
function Timing() { return <><PageHero eyebrow="Flux du contrôle de course" title="Chronométrage en direct" text="Les positions, temps au tour et écarts apparaîtront ici dès que la piste sera en direct." /><section className="track-grid bg-black py-24"><div className="mx-auto max-w-5xl px-5"><div className="border border-red-600/40 bg-neutral-950 p-8"><Radio className="h-5 w-5 text-red-500" /><h2 className="mt-5 font-display text-4xl font-black uppercase italic">Le chronométrage sera en direct<br />le week-end de course.</h2><a href="https://www.apex-timing.com/live-timing/karting-eupen/index.html" target="_blank" rel="noreferrer" className="mt-6 inline-flex text-xs font-black uppercase tracking-[.16em] text-red-500">Ouvrir Apex Timing <ArrowUpRight className="ml-2 h-4 w-4" /></a></div></div></section></>; }
function Drivers() { return <><PageHero eyebrow="Liste des engagés · Provisoire" title="Les pilotes" text="Les pilotes inscrits sont affichés ci-dessous. Cette liste est mise à jour à mesure que les inscriptions sont examinées." /><section className="bg-black py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Pilotes confirmés" title="La grille." /><div className="grid gap-px overflow-hidden border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-3">{drivers.map(([name, nation, team, cat]) => <article key={name} className="bg-neutral-950 p-5"><p className="text-[10px] font-black uppercase tracking-[.18em] text-red-500">{nationality[nation] || nation}</p><h3 className="mt-2 font-display text-xl font-black uppercase italic">{name}</h3><div className="mt-5 space-y-2 border-t border-white/10 pt-4 text-xs text-neutral-500"><p>Équipe <span className="float-right text-neutral-300">{team}</span></p><p>Catégorie <span className="float-right text-neutral-300">{category[cat] || cat}</span></p></div></article>)}</div></div></section></>; }
function Rules() { const list = [["Course équitable avant tout", "Respectez l'espace en piste et évitez les contacts."],["Matériel identique", "Les karts sont attribués par le contrôle de course."],["Comportement du pilote", "Le briefing est obligatoire et les instructions doivent être suivies immédiatement."],["Âge minimum", "Les pilotes doivent avoir au moins 12 ans."],["Poids de course", "Le poids de course est de 90 kg avec lest."],["Classement", "Les 60 meilleurs accèdent aux demi-finales et les 20 meilleurs à la finale."],["Équipement de sécurité", "Casque intégral, chaussures fermées et tenue adaptée obligatoires."]]; return <><PageHero eyebrow="Code sportif" title="Roulez vite. Roulez juste." text="Des règles claires permettent des courses serrées. Lisez l'essentiel avant votre arrivée." /><section className="track-grid bg-black py-20"><div className="mx-auto max-w-5xl px-5"><SectionTitle eyebrow="Règlement principal" title="Le règlement." />{list.map(([title, text], index) => <article key={title} className="mt-3 grid gap-4 border border-white/10 bg-neutral-950 p-5 sm:grid-cols-[52px_1fr]"><Number>{String(index + 1).padStart(2, "0")}</Number><div><h3 className="font-display text-xl font-black uppercase italic">{title}</h3><p className="mt-2 text-sm leading-6 text-neutral-500">{text}</p></div></article>)}</div></section></>; }
function Registration() { return <><PageHero eyebrow="Inscriptions" title="Prenez votre place" text="Les places ERW sont limitées. Complétez le formulaire officiel pour réserver votre place sur la grille." /><section className="track-grid bg-black py-20"><div className="mx-auto max-w-5xl px-5 text-center"><CheckCircle2 className="mx-auto h-14 w-14 text-red-500" /><h2 className="mt-5 font-display text-4xl font-black uppercase italic">Les inscriptions sont ouvertes.</h2><p className="mt-4 text-neutral-500">Droit d'inscription : €279 · Grille limitée à 200 pilotes · Cinq courses de qualification garanties.</p><a href={registrationUrl} target="_blank" rel="noreferrer" className="mt-7 inline-flex -skew-x-12 bg-red-600 px-6 py-4 text-xs font-black uppercase tracking-[.16em]"><span className="skew-x-12">Ouvrir le formulaire</span></a></div></section></>; }
function Contact() { return <><PageHero eyebrow="Contact paddock" title="Parlez au contrôle de course" text="Une question concernant les inscriptions, le format ou le week-end ? Contactez l'équipe ERW." /><section className="bg-black py-20"><div className="mx-auto grid max-w-5xl gap-4 px-5 md:grid-cols-2"><ContactCard label="E-mail" value="ertoworlds@gmail.com" /><ContactCard label="Téléphone" value="+32 456 79 24 04" /><ContactCard label="Lieu" value="Experience Factory · Industriestraße 37 · 4700 Eupen · Belgique" /><ContactCard label="Facebook" value="ERW · Eupen Road to Worlds" /></div></section></>; }
function ContactCard({ label, value }) { return <div className="border border-white/10 bg-neutral-950 p-5"><p className="text-[10px] font-black uppercase tracking-[.2em] text-red-500">{label}</p><p className="mt-2 text-sm text-neutral-300">{value}</p></div>; }
function Info({ title, copy }) { return <section className="track-grid bg-[#070707] py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Week-end de course" title={title} copy={copy} /><div className="grid gap-px overflow-hidden border border-white/10 bg-white/10 md:grid-cols-3">{[[Flag, "Le format", "Cinq courses de qualification par pilote."],[Trophy, "L'objectif", "Gagner sa place en grande finale."],[MapPin, "Le circuit", "Experience Factory Eupen, circuit indoor technique."]].map(([Icon, title, text]) => <article key={title} className="bg-[#0a0a0a] p-7"><Icon className="mb-10 h-7 w-7 text-red-500" /><h3 className="font-display text-2xl font-black uppercase italic">{title}</h3><p className="mt-3 text-sm leading-6 text-neutral-500">{text}</p></article>)}</div></div></section>; }
